/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"


float
calculate_prog_1(char *host,float n1,float n2,char opr,CLIENT *clnt)
{
	
	float  *result_1;
	inputs  sum_1_arg;
	float  *result_2;
	inputs  res_1_arg;
	float  *result_3;
	inputs  mult_1_arg;
	float  *result_4;
	inputs  div_1_arg;

if(opr=='+'){

	sum_1_arg.a=n1;
	sum_1_arg.b=n2;
	sum_1_arg.c=opr;
	result_1 = sum_1(&sum_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return *result_1;


}

else if(opr=='-'){
	res_1_arg.a=n1;
	res_1_arg.b=n2;
	res_1_arg.c=opr;
	result_2 = res_1(&res_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return *result_2;
}

else if(opr=='*'){
	mult_1_arg.a=n1;
	mult_1_arg.b=n2;
	mult_1_arg.c=opr;
	result_3 = mult_1(&mult_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return *result_3;
}

else if(opr=='/'){
	div_1_arg.a=n1;
	div_1_arg.b=n2;
	div_1_arg.c=opr;
	
	if(n2==0){
		printf("Division entre 0 no es posible.\n");
		exit(0);
	}else{
		result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	return *result_4;
	}
	
	
}





}


int
main (int argc, char *argv[])
{
	char *host;
	float a,b;
	CLIENT *clnt;

	char op;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	
	printf("Bienvenido a la calculadora de Pablo");
	
	printf("Inserte el primer numero :\n");
	scanf("%f",&a);

	printf("Inserte el segundo numero :\n");
	scanf("%f",&b);

	printf("Inserte operador :\n");
	printf("+ para Suma\n - para Resta\n * para Multiplicacion\n / para Division\n");
	scanf("%s",&op);
	
	


	host = argv[1];
	//calc_1 (host);

	#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATE_PROG, CALCULATE_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("El resultado es %.2f\n",calculate_prog_1(host,a,b,op,clnt));
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
exit (0);
}