/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	float a;
	float b;
	float c;
};
typedef struct inputs inputs;

struct vectores {
	struct {
		u_int float_array1_len;
		float *float_array1_val;
	} float_array1;
	struct {
		u_int float_array2_len;
		float *float_array2_val;
	} float_array2;
};
typedef struct vectores vectores;

#define CALCULATE_PROG1 0x2ffffffff
#define CALCULATE_VER1 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  float * sum_1(inputs *, CLIENT *);
extern  float * sum_1_svc(inputs *, struct svc_req *);
#define res 2
extern  float * res_1(inputs *, CLIENT *);
extern  float * res_1_svc(inputs *, struct svc_req *);
#define mult 3
extern  float * mult_1(inputs *, CLIENT *);
extern  float * mult_1_svc(inputs *, struct svc_req *);
#define div 4
extern  float * div_1(inputs *, CLIENT *);
extern  float * div_1_svc(inputs *, struct svc_req *);
#define pot 5
extern  float * pot_1(inputs *, CLIENT *);
extern  float * pot_1_svc(inputs *, struct svc_req *);
#define vector_sum 6
extern  float * vector_sum_1(vectores *, CLIENT *);
extern  float * vector_sum_1_svc(vectores *, struct svc_req *);
#define vector_res 7
extern  float * vector_res_1(vectores *, CLIENT *);
extern  float * vector_res_1_svc(vectores *, struct svc_req *);
#define vector_mult 8
extern  float * vector_mult_1(vectores *, CLIENT *);
extern  float * vector_mult_1_svc(vectores *, struct svc_req *);
extern int calculate_prog1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  float * sum_1();
extern  float * sum_1_svc();
#define res 2
extern  float * res_1();
extern  float * res_1_svc();
#define mult 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
#define pot 5
extern  float * pot_1();
extern  float * pot_1_svc();
#define vector_sum 6
extern  float * vector_sum_1();
extern  float * vector_sum_1_svc();
#define vector_res 7
extern  float * vector_res_1();
extern  float * vector_res_1_svc();
#define vector_mult 8
extern  float * vector_mult_1();
extern  float * vector_mult_1_svc();
extern int calculate_prog1_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);
extern  bool_t xdr_vectores (XDR *, vectores*);

#else /* K&R C */
extern bool_t xdr_inputs ();
extern bool_t xdr_vectores ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
