/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCUL_H_RPCGEN
#define _CALCUL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inputs {
	float a;
	float b;
	float c;
};
typedef struct inputs inputs;

#define CALCULATE_PROG 0x2fffffff
#define CALCULATE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sum 1
extern  float * sum_1(inputs *, CLIENT *);
extern  float * sum_1_svc(inputs *, struct svc_req *);
#define res 2
extern  float * res_1(inputs *, CLIENT *);
extern  float * res_1_svc(inputs *, struct svc_req *);
#define mult 3
extern  float * mult_1(inputs *, CLIENT *);
extern  float * mult_1_svc(inputs *, struct svc_req *);
#define div 4
extern  float * div_1(inputs *, CLIENT *);
extern  float * div_1_svc(inputs *, struct svc_req *);
extern int calculate_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sum 1
extern  float * sum_1();
extern  float * sum_1_svc();
#define res 2
extern  float * res_1();
extern  float * res_1_svc();
#define mult 3
extern  float * mult_1();
extern  float * mult_1_svc();
#define div 4
extern  float * div_1();
extern  float * div_1_svc();
extern int calculate_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inputs (XDR *, inputs*);

#else /* K&R C */
extern bool_t xdr_inputs ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCUL_H_RPCGEN */
